### ISSUE TITLE
Transformation gets triggered for missing field

### ISSUE THREAD

**Issue by apricote** [midknight41/map-factory#33]
Example Code:
```
const createMapper = require('map-factory');

const map = createMapper();

map
  .map("foo").to("foo")
  .map("foo").to("baz", foo => "val: " + foo);

const testObject = {
}

const result = map.execute(testObject);

console.dir(result); // { baz: 'val: null' }
```

IMHO, it feels a bit weird that a usual rule is not triggered for a missing field, but a transformation is.

The documentation also does not specify the expected behaviour, only thing i could find was:
> Mapping is explicit so unmapped fields are discarded.

**Comment by midknight41** [comment]
I agree the behaviour is inconsistent and probably undesirable. In my mind, if the source is absent the the transform should execute. I'll have a look at it. This should work for you in the meantime:

```js 
const map = createMapper();

map
  .map("ftoo").to("foo")
  .map("foo").to("baz", foo => { if(fab) return "val: " + fab });
```

**Comment by midknight41** [comment]
I've had a deeper look at this and I believe the current behaviour is actually correct. The logic is that once you provide a transform, map-factory can no longer guess your intention. As such, it hands over complete control to the developer to decide what to do. For an ```undefined``` or ```null``` you might want to create some structure...maybe you don't. I'll update the documentation to make the expected behaviour clearer.

That said, the behaviour could be modified provided that the person using map-factory can make that decision.

Something like this:

```js
const options = {
  alwaysTransform: false
};

const mapper = createMapper(options);
const source = {};

const result = mapper
  .map("foo").to("foo")
  .map("foo").to("baz", foo => return "val: " + foo)
  .execute(source);

expect(result).to.equal(source);
```

Changing the default behaviour would be a breaking change so I don't want to do that.

Would that work for you?

**Comment by apricote** [comment]
Absolutely, thank you :+1: 

By the way, i think the package is great and it really helps me.

**Comment by midknight41** [comment]
Glad you like it!

**Comment by midknight41** [comment]
Behaviour modification features added with ```1.7.0```. See [README](../blob/master/README.md#behaviour) for details.

Sorry it took so long. I had to do a major refactoring under the hood!

**Comment by apricote** [comment]
Again, thank you for all the work you are doing.
